version: '3.8'

services:
  app:
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydatabase
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
